### ISSUE TITLE
package dependencies in scripts referenced by the vignette

### ISSUE THREAD

**Issue by corybrunson** [nevrome/bleiglas#14]
The vignette refers to, but does not evaluate, scripts installed in "inst/workflow_example", which seem to depend not only on the **rnaturalearth** package but also on packages including **rgdal** that are required by specific steps. I'm not sure what the exact protocol is for such a setup (unless i've missed something, [the R extensions manual](https://cran.r-project.org/doc/manuals/R-exts.html#Package-Dependencies) is silent on this), but should these packages at least be listed as dependencies (presumably under `Suggests:`) in DESCRIPTION? This is indeed a question, not a recommendation, since the vignette can be generated (and **bleiglas** can be installed) without installing these.

_Part of [this JOSS review](https://github.com/openjournals/joss-reviews/issues/3092)._

**Comment by nevrome** [comment]
The setup is indeed unusual. Probably the Quickstart guide in the README would be more typical for a vignette. But then again vignettes are used for many different purposes (some times even whole research papers) and I think this extensive compilation of commented code could be useful for someone who really wants to use this package to the fullest.

I would rather not have the heavy dependencies for this specific case study in the package DESCRIPTION though. Instead I added explicit installation instructions at the beginning of the vignette in 8855d24. Do you think this makes it reasonably accessible?

**Comment by corybrunson** [comment]
Do you mean fb65fad3952ed3d9c8e387671258e1aa00527352? This looks good to me.

**Comment by nevrome** [comment]
Ah - yes - right. I must have copied the wrong hash. Thanks for searching yourself!
